 // Source code is unavailable, and was generated by the Fernflower decompiler.
 public class anahtarUret {
    public static byte[][] anahtar16Uret(byte[] key) {
       byte[][] anahtarListesi = new byte[16][];
       byte[] perAnahtar = yanFonksiyonlar.permutasyon(key, Tablolar.PC1);
       byte[] blok1 = bitIslemleri.byteDondur(perAnahtar, 0, Tablolar.PC1.length / 2);
       byte[] blok2 = bitIslemleri.byteDondur(perAnahtar, Tablolar.PC1.length / 2, Tablolar.PC1.length / 2);
 
       for(int i = 0; i < 16; ++i) {
          blok1 = anahtarKaydir(blok1, 28, Tablolar.kaydirma[i]);
          blok2 = anahtarKaydir(blok2, 28, Tablolar.kaydirma[i]);
          byte[] tamBlok = bitIslemleri.byteBirlestir(blok1, 28, blok2, 28);
          anahtarListesi[i] = yanFonksiyonlar.permutasyon(tamBlok, Tablolar.PC2);
       }
 
       return anahtarListesi;
    }
 
    private static byte[] anahtarKaydir(byte[] input, int len, int pas) {
       int nrBytes = (len - 1) / 8 + 1;
       byte[] out = new byte[nrBytes];
 
       for(int i = 0; i < len; ++i) {
          int val = bitIslemleri.bitDondur(input, (i + pas) % len);
          bitIslemleri.setBit(out, i, val);
       }
 
       return out;
    }
 }
 