
 // Source code is unavailable, and was generated by the Fernflower decompiler.
 public class bitIslemleri {
    public static byte[] byteDondur(byte[] blok, int konum, int n) {
       int byteUzunluk = (n - 1) / 8 + 1;
       byte[] out = new byte[byteUzunluk];
 
       for(int i = 0; i < n; ++i) {
          int val = bitDondur(blok, konum + i);
          setBit(out, i, val);
       }
 
       return out;
    }
 
    public static int bitDondur(byte[] blok, int bitKonum) {
       int bytePozisyon = bitKonum / 8;
       int bitPozisyon = 7 - bitKonum % 8;
       byte b = blok[bytePozisyon];
       int bit = b >> bitPozisyon & 1;
       return bit;
    }
 
    public static void setBit(byte[] blok, int bitKonum, int deger) {
       int bytePozisyon = bitKonum / 8;
       int bitPozisyon = bitKonum % 8;
       byte b1 = blok[bytePozisyon];
       b1 = (byte)('\uff7f' >> bitPozisyon & b1 & 255);
       byte b2 = (byte)(deger << 8 - (bitPozisyon + 1) | b1);
       blok[bytePozisyon] = b2;
    }
 
    public static byte[] byteAyir(byte[] in, int uzunluk) {
       int numOfBytes = (8 * in.length - 1) / uzunluk + 1;
       byte[] temp = new byte[numOfBytes];
 
       for(int i = 0; i < numOfBytes; ++i) {
          for(int j = 0; j < uzunluk; ++j) {
             int deger = bitDondur(in, uzunluk * i + j);
             setBit(temp, 8 * i + j, deger);
          }
       }
 
       return temp;
    }
 
    public static byte[] byteBirlestir(byte[] a, int aLen, byte[] b, int bLen) {
       int byteUzunluk = (aLen + bLen - 1) / 8 + 1;
       byte[] temp = new byte[byteUzunluk];
       int j = 0;
 
       int i;
       int val;
       for(i = 0; i < aLen; ++i) {
          val = bitDondur(a, i);
          setBit(temp, j, val);
          ++j;
       }
 
       for(i = 0; i < bLen; ++i) {
          val = bitDondur(b, i);
          setBit(temp, j, val);
          ++j;
       }
 
       return temp;
    }
 }
 