 // Source code is unavailable, and was generated by the Fernflower decompiler.

  // Source code is unavailable, and was generated by the Fernflower decompiler.
import java.nio.charset.StandardCharsets;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.MessageDigest;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.security.Signature;

public class imzalamaVeDogrulama {
   public static KeyPair generateKeyPair() throws Exception {
      KeyPairGenerator keyPairGenerator = KeyPairGenerator.getInstance("RSA");
      keyPairGenerator.initialize(2048);
      return keyPairGenerator.generateKeyPair();
   }

   public static byte[] hash(String text) throws Exception {
      MessageDigest digest = MessageDigest.getInstance("SHA-512");
      return digest.digest(text.getBytes(StandardCharsets.UTF_8));
   }

   public static byte[] sign(String text, PrivateKey privateKey) throws Exception {
      Signature signature = Signature.getInstance("SHA512withRSA");
      byte[] data = hash(text);
      signature.initSign(privateKey);
      signature.update(data);
      return signature.sign();
   }

   public static boolean verify(String text, byte[] signature, PublicKey publicKey) throws Exception {
      Signature verifier = Signature.getInstance("SHA512withRSA");
      verifier.initVerify(publicKey);
      byte[] data = hash(text);
      verifier.update(data);
      return verifier.verify(signature);
   }
}
