 // Source code is unavailable, and was generated by the Fernflower decompiler.
 public class Mesaj {
    private byte[] metin;
    private byte[] imza;
 
    public byte[] getMetin() {
       return this.metin;
    }
 
    public void setMetin(byte[] mesaj) {
       this.metin = mesaj;
    }
 
    public byte[] getImza() {
       return this.imza;
    }
 
    public void setImza(byte[] imza) {
       this.imza = imza;
    }
 }
 
