 // Source code is unavailable, and was generated by the Fernflower decompiler.
 public class SifrelemeDes {
    private static boolean kontrol;
 
    public static byte[] sifrele(byte[] mesaj, byte[][] anahtarListesi) {
       byte[] sifirByte = new byte[1];
       int uzunluk = 8 - mesaj.length % 8;
       byte[] blok = new byte[8];
       int count = 0;
       byte[] temp;
       if (uzunluk != 8) {
          kontrol = true;
          temp = new byte[mesaj.length + uzunluk];
       } else {
          kontrol = false;
          temp = new byte[mesaj.length];
       }
 
       int i;
       if (uzunluk == 8) {
          for(i = 0; i < mesaj.length; ++i) {
             if (i > 0 && i % 8 == 0) {
                blok = blokSifrele(blok, anahtarListesi, false);
                System.arraycopy(blok, 0, temp, i - 8, blok.length);
             }
 
             blok[i % 8] = mesaj[i];
          }
       } else {
          sifirByte = new byte[uzunluk];
          sifirByte[0] = -128;
 
          for(i = 1; i < uzunluk; ++i) {
             sifirByte[i] = 0;
          }
 
          for(i = 0; i < mesaj.length + uzunluk; ++i) {
             if (i > 0 && i % 8 == 0) {
                blok = blokSifrele(blok, anahtarListesi, false);
                System.arraycopy(blok, 0, temp, i - 8, blok.length);
             }
 
             if (i < mesaj.length) {
                blok[i % 8] = mesaj[i];
             } else {
                blok[i % 8] = sifirByte[count % 8];
                ++count;
             }
          }
       }
 
       if (blok.length == 8) {
          blok = blokSifrele(blok, anahtarListesi, false);
          System.arraycopy(blok, 0, temp, i - 8, blok.length);
       }
 
       return temp;
    }
 
    public static byte[] desifrele(byte[] mesaj, byte[][] anahtarListesi) {
       byte[] desifreEdilmisMesaj = new byte[mesaj.length];
       byte[] blok = new byte[8];
 
       int i;
       for(i = 0; i < mesaj.length; ++i) {
          if (i > 0 && i % 8 == 0) {
             blok = blokSifrele(blok, anahtarListesi, true);
             System.arraycopy(blok, 0, desifreEdilmisMesaj, i - 8, blok.length);
          }
 
          if (i < mesaj.length) {
             blok[i % 8] = mesaj[i];
          }
       }
 
       blok = blokSifrele(blok, anahtarListesi, true);
       System.arraycopy(blok, 0, desifreEdilmisMesaj, i - 8, blok.length);
       if (kontrol) {
          desifreEdilmisMesaj = yanFonksiyonlar.sifirByteSil(desifreEdilmisMesaj);
       }
 
       return desifreEdilmisMesaj;
    }
 
    private static byte[] blokSifrele(byte[] blok, byte[][] anahtarListe, boolean isDecrypt) {
       byte[] temp = new byte[blok.length];
       byte[] R = new byte[blok.length / 2];
       byte[] L = new byte[blok.length / 2];
       temp = yanFonksiyonlar.permutasyon(blok, Tablolar.BP);
       L = bitIslemleri.byteDondur(temp, 0, 32);
       R = bitIslemleri.byteDondur(temp, 32, 32);
 
       for(int i = 0; i < 16; ++i) {
          byte[] tempR = R;
          if (isDecrypt) {
             R = manglerFonksiyonu(R, anahtarListe[15 - i]);
          } else {
             R = manglerFonksiyonu(R, anahtarListe[i]);
          }
 
          R = yanFonksiyonlar.xorlama(L, R);
          L = tempR;
       }
 
       temp = bitIslemleri.byteBirlestir(R, 32, L, 32);
       temp = yanFonksiyonlar.permutasyon(temp, Tablolar.SP);
       return temp;
    }
 
    private static byte[] manglerFonksiyonu(byte[] R, byte[] K) {
       byte[] temp = yanFonksiyonlar.permutasyon(R, Tablolar.genisletmeTablo);
       temp = yanFonksiyonlar.xorlama(temp, K);
       temp = sbox_fonksiyonu(temp);
       temp = yanFonksiyonlar.permutasyon(temp, Tablolar.P);
       return temp;
    }
 
    private static byte[] sbox_fonksiyonu(byte[] temp) {
       temp = bitIslemleri.byteAyir(temp, 6);
       byte[] out = new byte[4];
       int halfByte = 0;
 
       for(int i = 0; i < temp.length; ++i) {
          byte byteDegeri = temp[i];
          int r = 2 * (byteDegeri >> 7 & 1) + (byteDegeri >> 2 & 1);
          int c = byteDegeri >> 3 & 15;
          int deger = Tablolar.sbox[i][r][c];
          if (i % 2 == 0) {
             halfByte = deger;
          } else {
             out[i / 2] = (byte)(16 * halfByte + deger);
          }
       }
 
       return out;
    }
 }
 
