
 // Source code is unavailable, and was generated by the Fernflower decompiler.
 import java.nio.charset.StandardCharsets;
 import java.util.Arrays;
 
 public class yanFonksiyonlar {

    public static void byteYaz(byte[] dizi) {
       byte[] var4 = dizi;
       int var3 = dizi.length;
 
       for(int var2 = 0; var2 < var3; ++var2) {
          byte b = var4[var2];
          String binaryString = String.format("%8s", Integer.toBinaryString(b & 255)).replace(' ', '0');
          System.out.print(binaryString + "   ");
       }
 
       System.out.println();
    }
 
    public static byte[] xorlama(byte[] a, byte[] b) {
       byte[] out = new byte[a.length];
 
       for(int i = 0; i < a.length; ++i) {
          out[i] = (byte)(a[i] ^ b[i]);
       }
 
       return out;
    }
 
    public static byte[] sifirByteSil(byte[] input) {
       int count = 0;
 
       for(int i = input.length - 1; input[i] == 0; --i) {
          ++count;
       }
 
       byte[] temp = new byte[input.length - count - 1];
       System.arraycopy(input, 0, temp, 0, temp.length);
       return temp;
    }
 
    public static byte[] stringToByte(String str) {
        return str.getBytes(StandardCharsets.ISO_8859_1);
    }
   
    public static String byteToString(byte[] byteArray) {
        return new String(byteArray, StandardCharsets.ISO_8859_1);
    }

 
    public static byte[] permutasyon(byte[] veri, int[] tablo) {
       int uzunluk = (tablo.length - 1) / 8 + 1;
       byte[] out = new byte[uzunluk];
 
       for(int i = 0; i < tablo.length; ++i) {
          int val = bitIslemleri.bitDondur(veri, tablo[i] - 1);
          bitIslemleri.setBit(out, i, val);
       }
 
       return out;
    }
 
    public static byte[] mesajiBirlestir(byte[] mesaj, byte[] imza) {
        byte[] birlesik = new byte[mesaj.length + imza.length];
        System.arraycopy(mesaj, 0, birlesik, 0, mesaj.length);
        System.arraycopy(imza, 0, birlesik, mesaj.length, imza.length);
        return birlesik;
    }

    public static byte[] mesajAyir(byte[] birlesik, int mesajBoyutu) {
        byte[] mesajBytes = new byte[mesajBoyutu];
        System.arraycopy(birlesik, 0, mesajBytes, 0, mesajBoyutu);
        return mesajBytes;
    }

    public static byte[] imzaAyir(byte[] birlesik, int mesajBoyutu,int imzaBoyutu) {
        byte[] imzaBytes = new byte[imzaBoyutu];
        System.arraycopy(birlesik, mesajBoyutu, imzaBytes, 0, imzaBoyutu);
        return imzaBytes;
    }


    public static void esitMi(Gonderici gonderici, Alici alici) {
       if (Arrays.equals(gonderici.getOrtakAnahtar(), alici.getOrtakAnahtar())) {
          System.out.println("Diffie-Hellman ba\u015far\u0131l\u0131.");
          System.out.println("Ana Kullan\u0131c\u0131 ortakAnahtar:   ");
          byteYaz(gonderici.getOrtakAnahtar());
          System.out.println("Di\u011fer kullan\u0131c\u0131 ortakAnahtar: ");
          byteYaz(alici.getOrtakAnahtar());
       } else {
          System.out.println("Diffie-Hellman ba\u015far\u0131s\u0131z.");
          System.out.println("Ana Kullan\u0131c\u0131 ortakAnahtar:   ");
          byteYaz(gonderici.getOrtakAnahtar());
          System.out.println("Di\u011fer kullan\u0131c\u0131 ortakAnahtar: ");
          byteYaz(alici.getOrtakAnahtar());
       }
 
    }
 }
 
